"use client";
import { useMemo, useState } from "react";
const draws = {
  lotofacil: { name: "Lotofácil", contest: 3779, date: "15/09/2026", numbers: [1,3,4,6,7,9,10,12,13,15,17,19,21,23,25], total: 25, color: "purple" },
  mega: { name: "Mega-Sena", contest: 3058, date: "15/09/2026", numbers: [14,23,53,56,57,60], total: 60, color: "green" },
  quina: { name: "Quina", contest: 6584, date: "15/09/2026", numbers: [5,13,39,58,80], total: 80, color: "violet" },
  milionaria: { name: "+Milionária", contest: 375, date: "15/09/2026", numbers: [4,6,10,21,31,38], total: 50, color: "blue" },
  dia: { name: "Dia de Sorte", contest: 1255, date: "15/09/2026", numbers: [2,7,12,19,24,27,31], total: 31, color: "amber" },
} as const;
type Modality = keyof typeof draws;
export default function ResultsPage() {
  const [selected, setSelected] = useState<Modality>("lotofacil"); const draw = draws[selected] as { name: string; contest: number; date: string; numbers: readonly number[]; total: number; color: string };
  const numbers = useMemo(() => Array.from({ length: draw.total }, (_, index) => index + 1), [draw.total]);
  return <div className="results-page"><header className="page-heading results-heading"><div><span className="eyebrow">Histórico de sorteios</span><h1>Resultados</h1><p>Consulte o concurso e veja como cada número caiu no volante.</p></div><label className="analysis-select"><span>Modalidade</span><select value={selected} onChange={(event) => setSelected(event.target.value as Modality)}>{Object.entries(draws).map(([slug, item]) => <option key={slug} value={slug}>{item.name}</option>)}</select></label></header><section className="draw-toolbar"><button className="draw-nav" type="button" aria-label="Concurso anterior">‹</button><div><span className="eyebrow">Resultado oficial</span><h2>Concurso {draw.contest}</h2><p>{draw.date} · {draw.numbers.length} dezenas sorteadas</p></div><button className="draw-nav" type="button" aria-label="Próximo concurso">›</button></section><section className="results-layout"><article className={`draw-result-card ${draw.color}`}><div className="draw-card-heading"><div><span className="eyebrow">Dezenas sorteadas</span><h2>{draw.name}</h2></div><span className="confirmed-badge">✓ Confirmado</span></div><div className="draw-numbers">{draw.numbers.map((number) => <span key={number}>{String(number).padStart(2, "0")}</span>)}</div><div className="draw-meta"><span>Soma <b>{draw.numbers.reduce((sum, number) => sum + number, 0)}</b></span><span>Pares <b>{draw.numbers.filter((number) => number % 2 === 0).length}</b></span><span>Ímpares <b>{draw.numbers.filter((number) => number % 2 !== 0).length}</b></span></div></article><article className="volante-card"><div className="draw-card-heading"><div><span className="eyebrow">Mini-volante</span><h2>Onde os números caíram</h2></div><span className="analysis-period">{draw.total} números</span></div><div className={`result-volante ${draw.color}`}>{numbers.map((number) => <span className={draw.numbers.includes(number) ? "hit" : ""} key={number}>{String(number).padStart(2, "0")}</span>)}</div><p className="analysis-note">As dezenas destacadas são as que saíram no concurso {draw.contest}.</p></article></section></div>;
}
